"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm"),assert=require("assert");
const root=process.argv[2]||__dirname,read=n=>fs.readFileSync(path.join(root,n),"utf8");
function extractObj(file,name){const s=read(file);let i=s.indexOf(`const ${name}`);assert(i>=0,`missing ${name}`);i=s.indexOf("=",i)+1;while(/\s/.test(s[i]))i++;const open=s[i],close=open==="{"?"}":"]";let depth=0,q=null,esc=false,td=0;for(let j=i;j<s.length;j++){const c=s[j],n=s[j+1];if(q){if(esc){esc=false;continue}if(c==="\\"){esc=true;continue}if(q==="`"){if(c==="`"&&td===0){q=null;continue}if(c==="$"&&n==="{"){td++;j++;continue}if(c==="}"&&td>0){td--;continue}}else if(c===q){q=null;continue}continue}if(c==='"'||c==="'"||c==="`"){q=c;continue}if(c===open)depth++;if(c===close){depth--;if(depth===0)return(new Function("return ("+s.slice(i,j+1)+")"))();}}throw new Error(`unclosed ${name}`)}
function extractAssignment(file,marker){const s=read(file);let i=s.indexOf(marker);assert(i>=0,`missing ${marker}`);i=s.indexOf("=",i)+1;while(/\s/.test(s[i]))i++;const open=s[i],close=open==="{"?"}":"]";let depth=0,q=null,esc=false,td=0;for(let j=i;j<s.length;j++){const c=s[j],n=s[j+1];if(q){if(esc){esc=false;continue}if(c==="\\"){esc=true;continue}if(q==="`"){if(c==="`"&&td===0){q=null;continue}if(c==="$"&&n==="{"){td++;j++;continue}if(c==="}"&&td>0){td--;continue}}else if(c===q){q=null;continue}continue}if(c==='"'||c==="'"||c==="`"){q=c;continue}if(c===open)depth++;if(c===close){depth--;if(depth===0)return(new Function("return ("+s.slice(i,j+1)+")"))();}}throw new Error(`unclosed ${marker}`)}
const curriculum=extractAssignment("platform-catalog-v300.js","window.KitsuneCurriculum");
const chapters=extractObj("app.js","chapters"),lessonData=extractObj("app.js","lessonData");Object.assign(lessonData,extractObj("course-v1.js","v1Lessons"));const enh=extractObj("chapter1-v02.js","chapterEnhance");for(const[id,e]of Object.entries(enh)){const d=lessonData[id];Object.assign(d,{goals:e.goals,formula:e.formula,quick:e.quick,summary:e.summary,challenge:e.challenge,interactive:e.interactive||null});d.examples=[d.example,e.extraExample];d.exercises=[...(d.exercises||[]),...(e.extraExercises||[])];}
const context={window:{KitsuneCurriculum:curriculum,KitsuneTheoryContent:{}},chapters,lessonData,structuredClone:global.structuredClone,console};context.window.window=context.window;vm.createContext(context);
vm.runInContext(read("curriculum-overlay-v310.js"),context);
for(const f of ["platform-content-v300.js","platform-content-grade8-algebra-v311.js","platform-content-grade8-frp-v311.js"])vm.runInContext(read(f),context,{filename:f});
for(const f of fs.readdirSync(root).filter(f=>/^platform-content-(?:grade(?:7|8|9|10|11)|oge|egeb|egep)-.*\.js$/.test(f)&&!["platform-content-grade8-algebra-v311.js","platform-content-grade8-frp-v311.js"].includes(f)).sort())vm.runInContext(read(f),context,{filename:f});
const topics=[];for(const tr of curriculum.tracks)for(const sec of tr.sections||[])for(const ch of sec.chapters||[])for(const tp of ch.topics||[])topics.push({track:tr.id,id:tp.id});
const keys=topics.map(t=>`${t.track}:${t.id}`),uniq=new Set(keys);assert.strictEqual(keys.length,551,"current curriculum topic count");assert.strictEqual(uniq.size,551,"curriculum IDs unique");
const theory=context.window.KitsuneTheoryContent;for(const k of keys)assert(theory[k],`missing authored content ${k}`);assert.strictEqual(keys.filter(k=>theory[k]).length,551,"551/551 authored");
const by={};for(const t of topics)by[t.track]=(by[t.track]||0)+1;assert.deepStrictEqual(by,{grade7:112,grade8:116,grade9:77,grade10:75,grade11:62,oge:37,"ege-basic":26,"ege-profile":46});
const g8=curriculum.tracks.find(t=>t.id==="grade8"),alg=g8.sections.find(s=>s.id==="g8-ready");assert.strictEqual(alg.chapters.length,9);assert.strictEqual(alg.chapters.reduce((n,c)=>n+c.topics.length,0),63);assert(!alg.chapters.some(c=>c.topics.some(t=>t.id==="g8-current-1")),"legacy launcher must be replaced by first-class topics");
const platform=read("platform-v300.js");assert(platform.includes("🧠 Углублённый разбор"));assert(platform.includes("📚 Полная теория — прочитать спокойно"));assert(platform.includes('data-v3-level="deep"'));assert(platform.includes('class="v3-deep-dive reveal" aria-hidden="true"'));
const idx=read("index.html");for(const f of ["platform-content-grade8-algebra-v311.js","platform-content-grade8-frp-v311.js","grade8-progress-bridge-v311.js"])assert(idx.includes(f),`index missing ${f}`);
// Every local script/style/image/manifest referenced by index must exist (ignore inline/data/external).
const refs=[...idx.matchAll(/(?:src|href)=["'](\.\/[^"'#?]+)[^"']*["']/g)].map(m=>m[1].replace(/^\.\//,""));for(const ref of refs)assert(fs.existsSync(path.join(root,ref)),`index asset missing: ${ref}`);
assert(!/new\s+MutationObserver\s*\(/.test(read("school-typography-ui-v3045.js")),"no global MutationObserver regression");
console.log(`PASS: alpha.7 current regression — ${keys.length}/${keys.length} curriculum topics authored, Grade 8=${by.grade8}, algebra modernized=63, assets/theory modes PASS`);
