const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),{spawnSync}=require('child_process');
const root=path.resolve(process.env.KITSUNE_QA_ROOT||path.join(__dirname,'../..')),source=JSON.parse(fs.readFileSync(path.join(__dirname,'source-content-sha256.json'),'utf8')),results=[];
const read=n=>fs.readFileSync(path.join(root,n),'utf8');const test=(name,fn)=>{try{const detail=fn();results.push({name,status:'PASS',detail});console.log('PASS',name,detail||'')}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message)}};
const all=(dir)=>fs.readdirSync(dir,{withFileTypes:true}).filter(x=>!['.git','node_modules','test-results'].includes(x.name)).flatMap(x=>x.isDirectory()?all(path.join(dir,x.name)):[path.join(dir,x.name)]);
test('Syntax of all application and regression JS',()=>{const files=all(root).filter(x=>/\.(m?js|cjs)$/.test(x));for(const f of files){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});assert.equal(r.status,0,r.stderr)}return files.length});
for(const file of ['regression-alpha7-current.test.js','regression-grade8-modernization-v311.test.js','regression-grade8-progress-bridge-v311.test.js'])test(file,()=>{const r=spawnSync(process.execPath,[path.join(root,file),root],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim()});
test('551 curriculum entries: current runtime, exercise schema and exam cross-links',()=>{
 const box={require,process:{argv:['node','test',root]},__dirname:root,console:{log(){}},structuredClone,global:{structuredClone}};vm.createContext(box);vm.runInContext(read('regression-alpha7-current.test.js')+'\nglobalThis.qaData={curriculum,theory};',box);
 const {curriculum,theory}=box.qaData;let topics=0,links=0,variants=0;
 for(const tr of curriculum.tracks)for(const s of tr.sections)for(const c of s.chapters)for(const t of c.topics){topics++;const d=theory[tr.id+':'+t.id];for(const k of ['title','lead','formula','why','remember','mistake','voice'])assert(d[k],tr.id+':'+t.id+' '+k);for(const k of ['simple','school','deep'])assert(d.levels[k]);assert(d.examples.length>=2);assert(d.exercises.length>=3);for(const e of d.exercises){assert(e.q&&Array.isArray(e.a)&&e.a.length&&e.hint)}for(const l of d.exam?.schoolLinks||[]){links++;assert(theory[l.trackId+':'+l.topicId]);}if(d.exam?.variantSize){variants++;assert.equal(d.exercises.length,d.exam.variantSize);}}
 assert.equal(topics,551);assert.equal(variants,9);return {topics,links,variants};
});
test('Lesson content byte-identical to provided WORK archive',()=>{const files=fs.readdirSync(root).filter(f=>/^platform-content.*\.js$|^(app|course-v1|chapter1-v02|course-theory-v120)\.js$/.test(f));for(const f of files)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex'),source[f],f);return files.length});
test('All index refs and lazy group refs exist and are in offline shell',()=>{const sw=read('sw.js'),assets=JSON.parse(sw.match(/const CORE_ASSETS=(\[[\s\S]*?\]);/)[1]);const idx=[...read('index.html').matchAll(/(?:src|href)=["'](\.\/[^"']+)["']/g)].map(m=>m[1]);const lazy=[...read('runtime-loader-v2395.js').matchAll(/"(\.\/[^"']+\.js\?v=[^"']+)"/g)].map(m=>m[1]);for(const ref of [...assets,...idx,...lazy]){assert(fs.existsSync(path.join(root,ref.split('?')[0])),ref);assert(assets.includes(ref),ref+' not precached')}return {index:idx.length,lazy:lazy.length,offline:assets.length};});
test('Manifest icons and CSS URLs resolve',()=>{const manifest=JSON.parse(read('manifest.json'));for(const icon of manifest.icons)assert(fs.existsSync(path.join(root,icon.src)));for(const f of all(root).filter(x=>x.endsWith('.css')))for(const m of fs.readFileSync(f,'utf8').matchAll(/url\(["']?([^\s)"']+)/g)){if(!/^(data:|https?:|#)/.test(m[1]))assert(fs.existsSync(path.resolve(path.dirname(f),m[1].split('?')[0])),m[1])}return manifest.icons.length});
test('Release identity is consistent',()=>{const version=JSON.parse(read('version.json')).version;assert.equal(version,'3.1.0-rc.2');assert(read('sw.js').includes(`const RELEASE="${version}"`));assert(read('sw.js').includes(`const CACHE="kitsune-math-${version}"`));assert(read('index.html').includes(`content="${version}"`));assert(read('platform-v300.js').includes(`const VERSION="${version}"`));return version;});
test('Exact worker URLs are cached; offline diagnostics recognizes current namespace',()=>{const assets=JSON.parse(read('sw.js').match(/const CORE_ASSETS=(\[[\s\S]*?\]);/)[1]);for(const f of ['math-engine-v130.js','kitsune-voice-v19.js','voice-stability-v2387.js'])for(const m of read(f).matchAll(/new Worker\(\s*["'](\.\/[^"']+)["']/g))assert(assets.includes(m[1]),m[1]);assert(read('offline-center-v200.js').includes('`kitsune-math-${VERSION}`'));assert(!read('offline-center-v200.js').includes('сама подготавливает'));});
test('Typography fraction axis and no whole-DOM formatter observer',()=>{const css=read('platform-v300.css');for(const v of ['display:inline-grid','vertical-align:middle','transform:translateY(-0.02em)','line-height:1.7'])assert(css.includes(v),v);assert(!/new\s+MutationObserver\s*\(/.test(read('school-typography-ui-v3045.js')))});
test('Voice runtime current: v2387 / worker v2386; explicit-only loading and cleanup',()=>{const main=read('voice-stability-v2387.js'),loader=read('runtime-loader-v2395.js'),worker=read('voice-asr-worker-v2386.js');assert(loader.includes('voice-stability-v2387.js'));assert(main.includes('./voice-asr-worker-v2386.js'));assert(main.includes('if(workerReady&&workerMode===requested)return true;'));assert(main.includes('await window.KitsuneLiveConversation?.release?.()'));assert(main.includes('epoch!==sessionEpoch'));assert(main.includes('acquired.getTracks().forEach(t=>t.stop())'));assert(!/\bfetch\s*\(/.test(main));assert(loader.includes("if(name==='assistant'&&background)return false"));assert(read('auto-setup-v210.js').includes('if(!manual)return false'));assert(!/^\s*schedule(?:Whisper|Brain)RestoreAfterUpdate\(\);/m.test(read('kitsune-voice-v19.js')+read('kitsune-brain-v18.js')));assert(worker.includes('language:"russian"'));return 'PASS code contract; hardware speech accuracy outside automated scope';});
fs.writeFileSync(path.join(__dirname,'static-results.json'),JSON.stringify(results,null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
